### ISSUE TITLE
Install on Ubuntu

### ISSUE THREAD

**Issue by gdbelvin** [JHUISI/charm#3]
The correct python3 path on ubuntu is
/usr/local/lib/python3.1/dist-packages

However, none of the standard system calls return this directory directly.

> > > distutils.sysconfig.get_python_lib(0, 0, '/usr/local')
> > > '/usr/local/lib/python3/dist-packages'
> > > distutils.sysconfig.get_python_lib(0, 1, '/usr/local')
> > > '/usr/local/lib/python3.1'
> > > distutils.sysconfig.get_python_lib(1, 0, '/usr/local')
> > > '/usr/local/lib/python3/dist-packages'
> > > distutils.sysconfig.get_python_lib(1, 1, '/usr/local')
> > > '/usr/local/lib/python3.1'

**Comment by jakinyele** [comment]
Yeah, that is a problem on Ubuntu, since there can be different versions and
enumerating all and verifying might be the only viable install option. Or we
can take this prefix distutils.sysconfig.get_python_lib(0, 1, '/usr/local'),
and then concatenate with the destination 'dist-packages' which is fairly
consistent in Ubuntu. What do you think?

Ayo.

**Comment by gdbelvin** [comment]
Are you aware of any way to enumerate the different install locations?  If so, I can code it up in between getting DABE working

**Comment by jakinyele** [comment]
This issue should be closed already, I think.
