### ISSUE TITLE
get rid of ec and integer distinctions for ecdsa and elgemal and Cramer-Shoup

### ISSUE THREAD

**Issue by imichaelmiers** [JHUISI/charm#37]
These schemes have separate ec and integer variants. Since we have a common group interface, this should be removed

**Comment by ChristinaLGarman** [comment]
This is currently not possible because the group interfaces do not line up perfectly.  We have group.random(G) in ecc which doesn't translate to integer.  There is also a group.randomGen() function in integer that isn't understood by ecc.  These disparities need to be resolved in order to use the common interface.

**Comment by ChristinaLGarman** [comment]
I _think_ group.randomGen() matches up with group.random(G) but I'm not sure.  They are used in the same places in the different files which leads me to believe they are performing the same function just in different settings.  If so, a common interface like group.random(G) for both of them would be ideal.

**Comment by ChristinaLGarman** [comment]
integer groups also don't recognize the call group.zr() that is used in ecdsa

**Comment by jakinyele** [comment]
The bigger issue is that there are details in integer-based schemes that have to be exposed (e.g., explicit use of p & q in DSA), but are actually encapsulated in group objs in the EC counterparts. We could clean up certain things obviously, but i don't think we can avoid the ec and integer distinctions.
